#!/bin/bash
#####
# Install composer
#####
if [ ! -e "/usr/bin/composer" ]
  then
    curl -sS https://getcomposer.org/installer | php
    mv /opt/codedeploy-agent/composer.phar /usr/bin/composer
  else
  	echo "Composer alrady installed..";
fi

#####
# Prepare for overwrite of php-fpm and nginx files
#####
#if [ -e "/etc/php/7.1/fpm/pool.d" ]
#  then
#    mv -f /etc/php/7.1/fpm/pool.d/www.conf /etc/php/7.1/fpm/pool.d/www.conf.bk
#fi
#if [ -e "/etc/nginx/nginx.conf" ]
#  then
#    mv -f /etc/nginx/nginx.conf /etc/nginx/nginx.conf.bk
#fi
#if [ -e "/etc/nginx/sites-enabled/magento.conf" ]
#  then
#    mv -f /etc/nginx/sites-enabled/magento.conf /etc/nginx/sites-enabled/magento.conf.bk
#fi

#####
# Create Magento web directory
#####
if [ ! -d "/var/www/magento2" ]
  then
    mkdir -p /var/www/magento2
    chmod -R 775 /var/www/magento2
    chown -R nginx:nginx /var/www/html/magento2
  else
  	echo "Web directory /var/www/magento already installed..";
fi

