#!/bin/bash
#####
# Move existing code base
#####
if [ -d "/var/www/magento2" ]
  then
    mv -f /var/www/magento2 /var/www/magento2.bk
  else
  	echo "Web directory /var/www/magento2 already installed..";
fi

#####
# Prepare to overwrite nginx vhost file (app.conf)
#####
if [ -e "/var/www/magento2/app.conf" ]
  then
    mv -f /var/www/magento2/app.conf /var/www/magento2/app.conf.bk
fi

