#!/bin/bash
sudo service nginx restart
sudo service php-fpm restart
chown -R nginx:nginx /var/www/magento2/var/
chown nginx:nginx /var/www/magento2
chmod 777 /var/www/magento2
find /var/www/magento2/ ! -name "media" | xargs -I {} chown nginx:nginx -R {}
find /var/www/magento2/ ! -name "media" | xargs -I {} chmod 775 -R {}
chmod -R 777 /var/www/magento2/var/
mkdir /var/www/magento2/var/cache
chmod -R 777 /var/www/magento2/var/cache

#####
# Remove last archived version
#####
sudo rm -rf /var/www/magento2.bk

